[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
rand = "0.8.5"
bevy = "0.7"
bevy_window_icon = { path = "../bevy_window_icon" }
winit = "0.26"